
DROP TABLE IF EXISTS STUDENTS;
DROP TABLE IF EXISTS SUBJECTS;

CREATE TABLE SUBJECTS (
    subjectId BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    subjectName VARCHAR(30) NOT NULL UNIQUE
);


CREATE TABLE STUDENTS (
    studentId SERIAL PRIMARY KEY,
    studentName VARCHAR(30) NOT NULL UNIQUE,
    studentEmail VARCHAR(150),
    subjectId BIGINT,
    FOREIGN KEY (subjectId) REFERENCES SUBJECTS(subjectId)
);
