
DROP TABLE IF EXISTS STUDENTS;
DROP TABLE IF EXISTS SUBJECTS;

CREATE TABLE SUBJECTS (
    SUBJECT_ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    SUBJECT_NAME VARCHAR(30) NOT NULL UNIQUE
);


CREATE TABLE STUDENTS (
    STUDENT_ID SERIAL PRIMARY KEY,
    STUDENT_NAME VARCHAR(30) NOT NULL UNIQUE,
    STUDENT_EMAIL VARCHAR(150),
    SUBJECT_ID BIGINT,
    FOREIGN KEY (SUBJECT_ID) REFERENCES SUBJECTS(SUBJECT_ID)
);
